language: rust

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

rust:
  - nightly

install:
  - pip3 install --user fire

jobs:
  - stage: "Build"
    name: "Rust build"
    script: cargo build --verbose --all
  - stage: "Test"
    name: "Rust tests"
    script: cargo test --verbose --all
